site_name: Pipewrench Docs
site_description: Documentation for the Pipewrench application found at app.pipewrench.co.uk
site_url: https://docs.pipewrench.co.uk

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Onboarding: getting-started/onboarding.md
      - Company Details: getting-started/company-details.md
      - "Branding & Logos": getting-started/branding.md
      - "Quickstart: New Customer -> Proposal": getting-started/quickstart.md
  - Customers:
      - Managing Customers: customers/managing-customers.md
      - Importing Customers: customers/importing-customers.md
      - Managing Customer Contacts: customers/managing-contacts.md
      - Importing Contacts: customers/importing-contacts.md
  - Items:
      - "Product & Service Items": items/managing-items.md
      - Importing Items: items/importing-items.md
  - Quotes:
      - "Creating & Editing Quotes": quotes/new-edit-quote.md
      - Converting Quotes to Invoices: quotes/convert-quote-invoice.md
  - Proposals:
      - "Creating & Editing Proposals": proposals/new-edit-proposal.md
      - AI Content Writer: proposals/ai-writer.md
  - Invoices:
      - "Creating & Editing Invoices": invoices/new-edit-invoice.md
      - "Payments & Receipts": invoices/payments-receipts.md
  - Image Library:
      - Image Library: images/image-library.md
      - Creating Images: images/creating-images.md
  - Settings:
      - Account Settings: settings/account.md
      - "Subscription & Billing": settings/billing.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch theme

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - def_list